name: Build
on: [push, pull_request]
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-amd64
          - linux-386
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
          - linux-arm
          - linux-arm64
          - linux-ppc64le
          - linux-s390x
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: "1.19.8"
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          set -euo pipefail

          echo "${TARGET}"
          case "${TARGET}" in
            linux-amd64)
              GOOS=linux GOARCH=amd64 make build
              ;;
            linux-386)
              GOOS=linux GOARCH=386 make build
              ;;
            darwin-amd64)
              GOOS=darwin GOARCH=amd64 make build
              ;;
            darwin-arm64)
              GOOS=darwin GOARCH=arm64 make build
              ;;
            windows-amd64)
              GOOS=windows GOARCH=amd64 make build
              ;;
            linux-arm)
              GOOS=linux GOARCH=arm make build
              ;;
            linux-arm64)
              GOOS=linux GOARCH=arm64 make build
              ;;
            linux-ppc64le)
              GOOS=linux GOARCH=ppc64le make build
              ;;
            linux-s390x)
              GOOS=linux GOARCH=s390x make build
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
