name: grpcProxy-tests
on: [push, pull_request]
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-amd64-grpcproxy-integration
        - linux-amd64-grpcproxy-e2e
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
      with:
        go-version: "1.19.8"
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        set -euo pipefail

        echo "${TARGET}"
        case "${TARGET}" in
          linux-amd64-grpcproxy-integration)
            GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-integration
            ;;
          linux-amd64-grpcproxy-e2e)
            GOOS=linux GOARCH=amd64 CPU=4 RACE=true make test-grpcproxy-e2e
            ;;
          *)
            echo "Failed to find target"
            exit 1
            ;;
        esac
