---
name: Robustness
on: [push, pull_request]
permissions: read-all
jobs:
  main:
    uses: ./.github/workflows/robustness-template.yaml
    with:
      etcdBranch: main
      count: 12
      testTimeout: 30m
      artifactName: main
      runs-on: "['ubuntu-latest-8-cores']"
